spring:
  application:
    name: digital-banking-app
  datasource:
    url: jdbc:postgresql://localhost:5432/digital-banking-app
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: allaoua

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
