spring:
  application:
    name: digital-banking-app
  datasource:
    url: jdbc:h2:mem:digital-banking-app
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
